---

- name: Check if hdsentinel is installed
  ansible.builtin.stat:
    path: "{{ hdsentinel_bin_path }}"
  register: hdsentinel_bin

- name: Install HDSentinel binary
  when: not hdsentinel_bin.stat.exists or hdsentinel_update | bool
  block:

    - name: Ensure unzip is installed
      ansible.builtin.package:
        name: unzip
        state: present
      delegate_to: localhost

    - name: Download hdsentinel binary
      ansible.builtin.get_url:
        url: "{{ hdsentinel_download_url }}"
        dest: /tmp/hdsentinel.zip
        mode: "0644"
      delegate_to: localhost

    - name: Unarchive hdsentinel binary
      ansible.builtin.unarchive:
        src: /tmp/hdsentinel.zip
        dest: /tmp/
      delegate_to: localhost

    - name: Propagate hdsentinel binary
      ansible.builtin.copy:
        src: /tmp/HDSentinel
        dest: "{{ hdsentinel_bin_path }}"
        mode: 0755
